
package Vista;


public class FormaCos extends javax.swing.JFrame {

    /**
     * Creates new form FormaCos
     */
    public FormaCos() {
        

 
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtDNIpa = new javax.swing.JTextField();
        txtNom = new javax.swing.JTextField();
        txtFechana = new javax.swing.JTextField();
        txtLugar = new javax.swing.JTextField();
        txtFechaemi = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaMostrar = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        btnRegresarc = new javax.swing.JButton();
        btnAceptarc = new javax.swing.JButton();
        btnCancelarc = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "CONSTANCIA DE VACUNA", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        jPanel2.setLayout(null);

        jLabel1.setText("DNI paciente");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(11, 37, 68, 16);

        jLabel2.setText("Nombre");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(11, 77, 44, 16);

        jLabel3.setText("Fecha de ");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(10, 120, 50, 16);

        jLabel4.setText("nacimiento");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(10, 140, 60, 16);

        jLabel5.setText("Lugar de");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(10, 170, 80, 16);

        jLabel6.setText("residencia");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(10, 190, 53, 16);

        jLabel8.setText("jLabel8");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(11, 528, 37, 16);
        jPanel2.add(txtDNIpa);
        txtDNIpa.setBounds(120, 30, 178, 37);
        jPanel2.add(txtNom);
        txtNom.setBounds(120, 80, 178, 37);
        jPanel2.add(txtFechana);
        txtFechana.setBounds(120, 120, 178, 37);

        txtLugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLugarActionPerformed(evt);
            }
        });
        jPanel2.add(txtLugar);
        txtLugar.setBounds(120, 170, 179, 37);
        jPanel2.add(txtFechaemi);
        txtFechaemi.setBounds(120, 220, 178, 37);

        txaMostrar.setColumns(20);
        txaMostrar.setRows(5);
        jScrollPane1.setViewportView(txaMostrar);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(10, 300, 278, 86);

        jLabel10.setText("Fecha de");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(10, 220, 47, 16);

        jLabel11.setText("emisión");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(10, 240, 42, 16);

        jLabel12.setText("Observaciones");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(10, 270, 77, 16);

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 320, 400));

        btnRegresarc.setText("REGRESAR");
        jPanel1.add(btnRegresarc, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 420, 110, 30));

        btnAceptarc.setText("ACEPTAR");
        jPanel1.add(btnAceptarc, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, 110, 30));

        btnCancelarc.setText("CANCELAR");
        btnCancelarc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarcActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancelarc, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 420, 110, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarcActionPerformed

    private void txtLugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLugarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLugarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormaCos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormaCos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormaCos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormaCos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormaCos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAceptarc;
    public javax.swing.JButton btnCancelarc;
    public javax.swing.JButton btnRegresarc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    public javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTextArea txaMostrar;
    public javax.swing.JTextField txtDNIpa;
    public javax.swing.JTextField txtFechaemi;
    public javax.swing.JTextField txtFechana;
    public javax.swing.JTextField txtLugar;
    public javax.swing.JTextField txtNom;
    // End of variables declaration//GEN-END:variables
}
