
package Vista;


public class FormaVacuna extends javax.swing.JFrame {

    /**
     * Creates new form FormaVacuna
     */
    public FormaVacuna() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtDNIpaci = new javax.swing.JTextField();
        txtPersona = new javax.swing.JTextField();
        txtAplica = new javax.swing.JTextField();
        txtLote = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cbxNomvacuna = new javax.swing.JComboBox<>();
        btnAceptarv = new javax.swing.JButton();
        btnRegresarv = new javax.swing.JButton();
        jProgressBar1 = new javax.swing.JProgressBar();
        btnCancelarv = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "REGISTRO DE VACUNA", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("DNI de paciente");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 128, 30));

        jLabel3.setText("Nombre vacuna");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 128, 30));

        jLabel4.setText("Lote");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 128, 30));

        jLabel5.setText("Fecha de aplicacion");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 128, 30));

        jLabel6.setText("Personal que aplico");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 128, 30));
        jPanel3.add(txtDNIpaci, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 144, 34));
        jPanel3.add(txtPersona, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, 144, 34));

        txtAplica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAplicaActionPerformed(evt);
            }
        });
        jPanel3.add(txtAplica, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 144, 34));
        jPanel3.add(txtLote, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 144, 34));

        jLabel7.setText("aaaa-mm-dd");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 110, -1));

        cbxNomvacuna.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Covid-19", "Influenza", "Hepatitis B" }));
        cbxNomvacuna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxNomvacunaActionPerformed(evt);
            }
        });
        jPanel3.add(cbxNomvacuna, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 150, 30));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 300, 330));

        btnAceptarv.setText("ACEPTAR");
        jPanel1.add(btnAceptarv, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, 90, 30));

        btnRegresarv.setText("REGRESAR");
        btnRegresarv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarvActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegresarv, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 390, 120, 30));
        jPanel1.add(jProgressBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 310, 20));

        btnCancelarv.setText("CANCELAR");
        btnCancelarv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarvActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancelarv, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 390, 120, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 378, 455));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtAplicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAplicaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAplicaActionPerformed

    private void cbxNomvacunaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxNomvacunaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxNomvacunaActionPerformed

    private void btnRegresarvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegresarvActionPerformed

    private void btnCancelarvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarvActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormaVacuna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormaVacuna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormaVacuna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormaVacuna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormaVacuna().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAceptarv;
    public javax.swing.JButton btnCancelarv;
    public javax.swing.JButton btnRegresarv;
    public javax.swing.JComboBox<String> cbxNomvacuna;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel4;
    public javax.swing.JLabel jLabel5;
    public javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    public javax.swing.JPanel jPanel1;
    public javax.swing.JPanel jPanel3;
    public javax.swing.JProgressBar jProgressBar1;
    public javax.swing.JTextField txtAplica;
    public javax.swing.JTextField txtDNIpaci;
    public javax.swing.JTextField txtLote;
    public javax.swing.JTextField txtPersona;
    // End of variables declaration//GEN-END:variables
}
